In [30]:
# import the necessary libraries
import pandas as pd

In [ ]:
# Read the data file
df = pd.read_csv("file_path.csv")

## 1. How big is the Data ?

In [11]:
# Use df.shape to quickly see the number of rows and columns to understand the scale of the data.
df.shape

(50000, 15)

## 2. How Data looks like ??

In [12]:
#  Use df.head() to look at the first few rows, or df.sample() to take a random sample to avoid bias from sorted data.
df.sample(5)

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance
8507,TX008508,AC00421,94.91,4/5/2021,Credit,New York,D000436,182.225.2.156,M092,Online,20,Student,72,1,1152.20
44951,TX044952,AC00445,198.37,6/17/2022,Credit,Las Vegas,D000181,32.71.250.58,M078,Online,19,Student,30,1,229.02
20986,TX020987,AC00470,271.13,4/26/2021,Credit,Houston,D000534,150.231.20.169,M007,Branch,26,Engineer,134,1,6609.30
17650,TX017651,AC00139,10.31,6/5/2022,Debit,Austin,D000531,55.139.104.163,M004,ATM,59,Doctor,58,5,7155.04
16311,TX016312,AC00361,129.80,9/7/2025,Debit,San Antonio,D000634,221.206.44.63,M031,Branch,22,Student,146,1,961.65

## 3. Data type of columns

In [14]:
#  Use df.info() to see the data types of each column (numerical, object/string) and memory usage. 
#  This helps identify columns needing type conversion.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   TransactionID        50000 non-null  str
 1   AccountID            50000 non-null  str
 2   TransactionAmount    50000 non-null  float64
 3   TransactionDate      50000 non-null  str
 4   TransactionType      50000 non-null  str
 5   Location             50000 non-null  str
 6   DeviceID             50000 non-null  str
 7   IP Address           50000 non-null  str
 8   MerchantID           50000 non-null  str
 9   Channel              50000 non-null  str
 10  CustomerAge          50000 non-null  int64
 11  CustomerOccupation   50000 non-null  str
 12  TransactionDuration  50000 non-null  int64
 13  LoginAttempts        50000 non-null  int64
 14  AccountBalance       50000 non-null  float64
dtypes: float64(2), int64(3), str(10)
memory usage: 5.7 MB

## 4. Missing values

In [ ]:
# Use df.isnull().sum() to get the exact count of missing values per column, which informs your cleaning strategy.
df.isnull().sum()

TransactionID          0
AccountID              0
TransactionAmount      0
TransactionDate        0
TransactionType        0
Location               0
DeviceID               0
IP Address             0
MerchantID             0
Channel                0
CustomerAge            0
CustomerOccupation     0
TransactionDuration    0
LoginAttempts          0
AccountBalance         0
dtype: int64

## 5. Mathematical summary

In [17]:
# Use df.describe() to get statistical insights (mean, standard deviation, min, max, quartiles) for numerical columns.
df.describe()

,TransactionAmount,CustomerAge,TransactionDuration,LoginAttempts,AccountBalance
count,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000
mean,297.872214,44.647600,118.965320,1.12684,5122.738301
std,292.818888,17.800293,70.000681,0.60936,3904.266887
min,0.240000,18.000000,10.000000,1.00000,101.250000
25%,82.897500,27.000000,63.000000,1.00000,1508.720000
50%,209.355000,45.000000,111.000000,1.00000,4735.410000
75%,409.625000,59.000000,161.000000,1.00000,7713.670000
max,2060.590000,80.000000,300.000000,5.00000,14977.990000

## 6. Duplicate values

In [19]:
#  Use df.duplicated().sum() to check if any rows are repeated.
df.duplicated().sum()

np.int64(0)

## 7. Correlation between columns

In [ ]:
df.corr()

In [ ]:
df.corr()['CustomerAge']